import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';
import {
  Download, FileText, CalendarCheck, Users, TrendingUp, Briefcase,
  Star, IndianRupee, Clock, Mail, CheckCircle
} from 'lucide-react';

// ─── Types ──────────────────────────────────────────────────
type ReportData = {
  semester: string;
  generatedAt: string | null;
  autoGenerated: boolean;
  totalSessions: number;
  totalStudentsGuided: number;
  actionCompletionRate: number;
  milestones: {
    internshipSecured: number;
    jobOfferReceived: number;
    interviewCalls: number;
    higherStudiesApplied: number;
  };
  topAlumni: { name: string; outcomes: number; rating: number }[];
  guidedVsNon: {
    guidedMilestones: number;
    nonGuidedMilestones: number;
  };
  costPerSession: number;
  costPerOutcome: number;
  totalSpend: number;
};

// ─── Mock Data ──────────────────────────────────────────────
const REPORTS: ReportData[] = [
  {
    semester: 'Spring 2026',
    generatedAt: null,
    autoGenerated: false,
    totalSessions: 187,
    totalStudentsMentored: 142,
    actionCompletionRate: 68,
    milestones: { internshipSecured: 42, jobOfferReceived: 28, interviewCalls: 89, higherStudiesApplied: 15 },
    topMentors: [
      { name: 'Vikram Rao', outcomes: 18, rating: 4.8 },
      { name: 'Ritu Kapoor', outcomes: 15, rating: 4.7 },
      { name: 'Anita Desai', outcomes: 14, rating: 4.9 },
      { name: 'Suresh Kumar', outcomes: 11, rating: 4.6 },
      { name: 'Neha Gupta', outcomes: 9, rating: 4.8 },
    ],
    mentoredVsNon: { mentoredMilestones: 134, nonMentoredMilestones: 40 },
    costPerSession: 345,
    costPerOutcome: 742,
    totalSpend: 64515,
  },
  {
    semester: 'Fall 2025',
    generatedAt: '2025-12-31T23:59:00',
    autoGenerated: true,
    totalSessions: 156,
    totalStudentsMentored: 118,
    actionCompletionRate: 62,
    milestones: { internshipSecured: 35, jobOfferReceived: 22, interviewCalls: 72, higherStudiesApplied: 11 },
    topMentors: [
      { name: 'Ritu Kapoor', outcomes: 16, rating: 4.7 },
      { name: 'Vikram Rao', outcomes: 14, rating: 4.8 },
      { name: 'Amit Patel', outcomes: 10, rating: 4.5 },
      { name: 'Anita Desai', outcomes: 9, rating: 4.9 },
      { name: 'Suresh Kumar', outcomes: 8, rating: 4.6 },
    ],
    mentoredVsNon: { mentoredMilestones: 108, nonMentoredMilestones: 32 },
    costPerSession: 328,
    costPerOutcome: 718,
    totalSpend: 51168,
  },
];

const SEMESTERS = ['Spring 2026', 'Fall 2025'];

// ─── Component ──────────────────────────────────────────────
const SemesterReport = () => {
  const { toast } = useToast();
  const [selectedSemester, setSelectedSemester] = useState('Spring 2026');
  const [isGenerating, setIsGenerating] = useState(false);

  const report = REPORTS.find(r => r.semester === selectedSemester);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      toast({ title: 'Report Generated', description: `Semester report for ${selectedSemester} has been generated successfully.` });
    }, 2000);
  };

  const handleExportPDF = () => {
    toast({ title: 'PDF Export Started', description: 'Your semester report is being prepared for download with Vel Tech University and Grotalks branding.' });
    // In production, this would generate an actual PDF
    setTimeout(() => {
      toast({ title: 'PDF Ready', description: 'Report downloaded successfully.' });
    }, 1500);
  };

  const handleEmailNotify = () => {
    toast({ title: 'Email Sent', description: 'Admin has been notified that the semester report is ready.' });
  };

  if (!report) return null;

  const totalMilestones = report.milestones.internshipSecured + report.milestones.jobOfferReceived + report.milestones.interviewCalls + report.milestones.higherStudiesApplied;
  const totalComparisonMilestones = report.mentoredVsNon.mentoredMilestones + report.mentoredVsNon.nonMentoredMilestones;
  const mentoredPct = totalComparisonMilestones > 0 ? Math.round((report.mentoredVsNon.mentoredMilestones / totalComparisonMilestones) * 100) : 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Semester Report</h1>
          <p className="text-muted-foreground text-sm mt-1">Generate and export comprehensive semester reports</p>
        </div>
        <div className="flex gap-2">
          <Select value={selectedSemester} onValueChange={setSelectedSemester}>
            <SelectTrigger className="w-44"><SelectValue /></SelectTrigger>
            <SelectContent>
              {SEMESTERS.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Report Status */}
      <Card>
        <CardContent className="p-4 flex flex-col sm:flex-row items-start sm:items-center gap-4">
          <div className="flex items-center gap-3 flex-1">
            <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <FileText className="h-5 w-5 text-primary" />
            </div>
            <div>
              <p className="font-medium">{selectedSemester} Report</p>
              <p className="text-xs text-muted-foreground">
                {report.generatedAt
                  ? `Generated on ${new Date(report.generatedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}`
                  : 'Not yet generated'}
                {report.autoGenerated && <Badge variant="secondary" className="ml-2 text-[10px]">Auto-generated</Badge>}
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleGenerate} disabled={isGenerating}>
              {isGenerating ? <Clock className="h-4 w-4 mr-1 animate-spin" /> : <CheckCircle className="h-4 w-4 mr-1" />}
              {isGenerating ? 'Generating...' : 'Generate Now'}
            </Button>
            <Button size="sm" onClick={handleExportPDF}>
              <Download className="h-4 w-4 mr-1" /> Export PDF
            </Button>
            <Button variant="ghost" size="sm" onClick={handleEmailNotify}>
              <Mail className="h-4 w-4" />
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Key Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
              <CalendarCheck className="h-5 w-5 text-primary" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Total Sessions</p>
              <p className="text-lg font-bold">{report.totalSessions}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-success/10 flex items-center justify-center shrink-0">
              <Users className="h-5 w-5 text-success" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Students Mentored</p>
              <p className="text-lg font-bold">{report.totalStudentsMentored}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-warning/10 flex items-center justify-center shrink-0">
              <TrendingUp className="h-5 w-5 text-warning" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Action Completion</p>
              <p className="text-lg font-bold">{report.actionCompletionRate}%</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
              <Briefcase className="h-5 w-5 text-primary" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Total Milestones</p>
              <p className="text-lg font-bold">{totalMilestones}</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Career Milestones Breakdown */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Career Milestones Achieved</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: 'Internship Secured', value: report.milestones.internshipSecured, icon: Briefcase, color: 'text-success' },
              { label: 'Job Offer Received', value: report.milestones.jobOfferReceived, icon: FileText, color: 'text-success' },
              { label: 'Interview Calls', value: report.milestones.interviewCalls, icon: Star, color: 'text-warning' },
              { label: 'Higher Studies', value: report.milestones.higherStudiesApplied, icon: TrendingUp, color: 'text-primary' },
            ].map(item => (
              <div key={item.label} className="bg-muted/50 rounded-lg p-3 text-center">
                <item.icon className={`h-5 w-5 mx-auto mb-1 ${item.color}`} />
                <p className="text-2xl font-bold">{item.value}</p>
                <p className="text-xs text-muted-foreground">{item.label}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Top 5 Mentors */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Top 5 Mentors by Student Outcomes</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {report.topMentors.map((mentor, i) => (
              <div key={mentor.name} className="flex items-center gap-3">
                <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center text-sm font-bold text-primary shrink-0">
                  {i + 1}
                </div>
                <div className="flex-1">
                  <p className="text-sm font-medium">{mentor.name}</p>
                  <div className="flex items-center gap-1 text-xs text-muted-foreground">
                    <Star className="h-3 w-3 text-warning fill-warning" /> {mentor.rating}
                  </div>
                </div>
                <Badge variant="secondary">{mentor.outcomes} outcomes</Badge>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Mentored vs Non-Mentored */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Mentored vs Non-Mentored Comparison</CardTitle>
          <CardDescription>Career milestone distribution between mentored and non-mentored students</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <div className="flex h-8 rounded-full overflow-hidden bg-muted">
              <div className="bg-primary flex items-center justify-center text-xs font-medium text-primary-foreground" style={{ width: `${mentoredPct}%` }}>
                {report.mentoredVsNon.mentoredMilestones} ({mentoredPct}%)
              </div>
              <div className="bg-muted-foreground/30 flex items-center justify-center text-xs font-medium text-foreground" style={{ width: `${100 - mentoredPct}%` }}>
                {report.mentoredVsNon.nonMentoredMilestones} ({100 - mentoredPct}%)
              </div>
            </div>
            <div className="flex gap-4 text-xs text-muted-foreground">
              <span className="flex items-center gap-1"><div className="h-2 w-2 rounded-sm bg-primary" /> Mentored Students</span>
              <span className="flex items-center gap-1"><div className="h-2 w-2 rounded-sm bg-muted-foreground/30" /> Non-Mentored Students</span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Cost Analysis */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Cost Analysis</CardTitle>
          <CardDescription>Financial breakdown based on university wallet spend</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-muted/50 rounded-lg p-4 text-center">
              <IndianRupee className="h-5 w-5 mx-auto text-primary mb-1" />
              <p className="text-2xl font-bold">₹{report.totalSpend.toLocaleString()}</p>
              <p className="text-xs text-muted-foreground">Total Spend</p>
            </div>
            <div className="bg-muted/50 rounded-lg p-4 text-center">
              <IndianRupee className="h-5 w-5 mx-auto text-warning mb-1" />
              <p className="text-2xl font-bold">₹{report.costPerSession}</p>
              <p className="text-xs text-muted-foreground">Cost per Session</p>
            </div>
            <div className="bg-muted/50 rounded-lg p-4 text-center">
              <IndianRupee className="h-5 w-5 mx-auto text-success mb-1" />
              <p className="text-2xl font-bold">₹{report.costPerOutcome}</p>
              <p className="text-xs text-muted-foreground">Cost per Outcome</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Auto-generation notice */}
      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="p-4 flex items-start gap-3">
          <Clock className="h-5 w-5 text-primary mt-0.5" />
          <div>
            <p className="text-sm font-medium">Automatic Semester Reports</p>
            <p className="text-xs text-muted-foreground mt-0.5">
              Reports are automatically generated at the end of each semester. The admin will receive an email notification when the report is ready for review and export.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default SemesterReport;
